#!/usr/bin/env python

#TraCeR - a tool to reconstruct TCR sequences from single-cell RNA-seq data#
#Please see README and LICENCE for details of use and licence conditions.  #
#This software was written by Mike Stubbington (mstubb@ebi.ac.uk) from the #
#Teichmann Lab, EMBL-EBI (www.teichlab.org). Latest versions are available #
#for download at www.github.com/teichlab/tracer.                           #

